apiVersion: apps/v1
kind: Deployment
metadata:
  name: apuestas-service
  namespace: vidalcasino
  labels:
    app: apuestas-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: apuestas-service
  template:
    metadata:
      labels:
        app: apuestas-service
    spec:
      containers:
        - name: apuestas
          image: 088950558880.dkr.ecr.us-east-1.amazonaws.com/casino/apuestas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          envFrom:
            - secretRef:
                name: casino-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/apuestas/readyz
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/apuestas/livez
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
